# Generated by Django 3.0.3 on 2020-03-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': ['-start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='promo_image',
            field=models.ForeignKey(blank=True, help_text='Event promo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
