# Generated by Django 3.0.3 on 2020-02-24 18:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('code', models.CharField(help_text='An Identifier for the room.', max_length=50, verbose_name='Room Identifier')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='A short description of the room.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='The room price per night.', max_digits=10, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RoomPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('room', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.RoomPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(default='new', help_text='The status of the reservation.', max_length=50, verbose_name='Status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='The price the room rented for.', max_digits=10, null=True, verbose_name='Price')),
                ('room', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.RoomPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', wagtail.core.fields.RichTextField(verbose_name='Description')),
                ('room', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rooms.RoomPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
