# Generated by Django 3.0.3 on 2020-02-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='name',
            field=models.CharField(default='', help_text='The name of the person reserving the room.', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
