# Generated by Django 3.0.3 on 2020-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200304_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sport',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sport',
            field=models.ManyToManyField(related_name='_homepage_sport_+', to='home.WaterSport'),
        ),
    ]
