# Generated by Django 3.0.3 on 2020-03-04 06:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200304_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sport',
        ),
        migrations.CreateModel(
            name='HomePageSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_placement', to='home.HomePage')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.WaterSport')),
            ],
            options={
                'verbose_name': 'Water Sport placement',
                'verbose_name_plural': 'Water Sport placements',
            },
        ),
    ]
