# Generated by Django 3.0.3 on 2020-03-05 04:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0008_auto_20200304_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The cafe item title as you'd like it to be seen by the public", max_length=255, verbose_name='title')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='Write some promotional copy', null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Cafe image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'cafe items',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='cafe_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Enter the description for the cafe section on the home page.', null=True, verbose_name='Cafe Section Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cafe_title',
            field=models.CharField(blank=True, help_text='Enter the title for the cafe section on the home page.', max_length=255, verbose_name='Cafe Section Title'),
        ),
        migrations.CreateModel(
            name='HomePageCafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.CafeItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_placement', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Cafe placement',
                'verbose_name_plural': 'Cafe placements',
            },
        ),
    ]
