# Generated by Django 3.0.3 on 2020-03-06 04:50

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200305_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_us_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Enter the description for the Contact us section on the home page.', null=True, verbose_name='Contact Us Section Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_us_title',
            field=models.CharField(blank=True, help_text='Enter the title of the contact us section.', max_length=255, verbose_name='Contact Us Title'),
        ),
    ]
